### ISSUE TITLE
Drupal 11 support

### ISSUE THREAD

**Issue by agentrickard** [kevinquillen/recipe-generator#8]
I think the only blocker to Drupal 11 is composer.

Can we try adding `"drupal/core": "^10 || ^11",`  for testing?

Would also need drush `|| ^13`

**Comment by itamair** [comment]
this looks strictly related to this one: https://github.com/kevinquillen/recipe-generator/issues/6

FYI ... as it looks some responsiveness is lacking on this repo (probably because it is an old, one, not supported anymore, don't clearly know ...) BUT still there is not any kind of automatic / guided help in creating a Drupal Recipe (out there) so this still looks something theoretically helpful in introducing how to generate those Recipes,
I just also made this git for of mine:
https://github.com/itamair/recipe-generator

and also created a new parallel packagist project here (to eventually `composer require` from):
https://packagist.org/packages/itamair/recipe-generator

that looks (at some level) still working (not breaking) with Drupal 11 and Drush 13 ...

**Comment by kevinquillen** [comment]
A 2.0.x branch has been started that just merged D11 compatibility so the 1.0.x branch does not break.
